name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          rebar3-version: 3.15.2
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-24.1-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-24.1-1-
      - name: Elvis
        run: rebar3 format --verify

  lint:
    name: "Elvis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          rebar3-version: 3.15.2
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-24.1-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-24.1-1-
      - name: Elvis
        run: rebar3 lint

  dialyzer:
    name: "Dialyzer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          rebar3-version: 3.15.2
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-24.1-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-24.1-1-
      - name: Dialyzer
        run: rebar3 dialyzer

  eunit:
    name: EUnit on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        otp_version: ["24.1", "23.3.1", "22.3.4.9", "21.3.8.17"]
        os: [ubuntu-latest]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          rebar3-version: 3.15.2
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-${{ matrix.otp_version }}-1-
      - name: Compile
        run: rebar3 compile
      - name: EUnit
        run: rebar3 eunit --cover

  ct:
    name: CT on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        otp_version: ["24.1", "23.3.1", "22.3.4.9", "21.3.8.17"]
        os: [ubuntu-latest]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          rebar3-version: 3.15.2
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            build-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-build-${{ matrix.otp_version }}-1-
      - name: Compile
        run: rebar3 compile
      - name: Common Test
        run: rebar3 ct --cover
